### ISSUE TITLE
Larger hint size in DoublePIR than SimplePIR?

### ISSUE THREAD

**Issue by kzhong130** [ahenzinger/simplepir#1]
Hi there,

Thank you so much for making this great project open-sourced! I have tried it out myself but found some weird behavior for some parameters. In the paper, it mentioned that the hint size in DoublePIR should be smaller than SimplePIR. 

However, when I tried out with the command `LOG_N=16 D=28672 go test -run=BW`. The output seems to show that the hind size (which I believe is included in `Offline download`) is around 50GB in DoublePIR which is way much bigger than the hint size in SimplePIR. I wonder is this the expected behavior or not?

The log is attached here
```
Working with: n=1024; db size=2^27 (l=14780, m=13108); logq=32; p=833; sigma=6.400000
Total packed DB size is ~224.073226 MB
Executing with entries consisting of 28672 (>= 1) bits; p is 833; packing factor is 0; number of DB elems per entry is 2956.
		Offline download: 59120 KB
		Online upload: 51 KB
		Online download: 57 KB
Working with: n=1024; db size=2^27 (l=3148, m=65536); logq=32; p=552; sigma=6.400000
Total packed DB size is ~224.012773 MB
Executing with entries consisting of 28672 (>= 1) bits; p is 552; packing factor is 0; number of DB elems per entry is 3148.
		Offline download: 51576832 KB
		Online upload: 256 KB
		Online download: 100785 KB
PASS
ok  	simplepir	0.043s
```
Thank you again for taking the time to read this long message! I really appreciate it if you have any hints about this behavior.

**Comment by ahenzinger** [comment]
Hi,

Thank you for your great question!

You are correct that the offline download is equal to the hint size. The reason why the DoublePIR hint size is large in your example is because the database has large entries (namely, each database entry consists of more than 3 KB). As described in section 5.2 of the [paper](https://eprint.iacr.org/2022/949.pdf), the hint size in DoublePIR scales linearly with the database's entry size. On databases with entries of size ~1 byte or less, the hint size in DoublePIR is 16 MB (and thus, on large enough databases, smaller than in SimplePIR). However, on databases with larger entries, the DoublePIR hint size increases, as displayed in Figure 6. For a database of the dimensions that you suggest, SimplePIR would achieve better offline and online communication than DoublePIR (as the communication in SimplePIR scales only with the square-root of the database's entry size -- see section 4.3). 

I hope this helps, and please let me know if you have any more questions.

Best,
Alexandra

**Comment by kzhong130** [comment]
Thank you so much for the response! That makes sense to me.
