### ISSUE TITLE
About the security of server's database

### ISSUE THREAD

**Issue by matsutakk** [ahenzinger/simplepir#3]
Hi, from japan, thanks for intriguing work. 

I've read your paper and would like to know one thing.
I might misunderstand, but, does one query reveals the j-th column all information of the dabase to clients?

I wonder that if the client is malicious, they can obtain all information of j-th column by doing Recover algorithm in Figure 2 with i-th row (0 <= i <= √N). Is it setting of your paper?

Thank you.

**Comment by ahenzinger** [comment]
Yes, you are right that, in this work, we provide client privacy (i.e., the server does not learn which index the client is reading), but not server privacy (i.e., the client can learn as much of the server's database as it wants). In particular, as you point out, in SimplePIR the client can recover an entire column of the database on each query.

There are natural ways to add server privacy to such a PIR scheme. One way is to use Oblivious Pseudorandom Functions (OPRFs) so that the server can randomly "mask" all data records except for the one the client is reading. This is described in more detail in section E.1 of this work: https://eprint.iacr.org/2019/1483.pdf.

I hope this helps, and please let me know if you have any more questions.

**Comment by matsutakk** [comment]
Thank you for reply!

I checked section E.1 in the paper and learned the SPIR is the thing I was thinking about.

It really helped, thanks.

**Comment by matsutakk** [comment]
Sorry, one more question.

Where does your code handle modulus?

I mean, say, MatrixMul( or matMul) function does not mod. How it works?

**Comment by ahenzinger** [comment]
We take the ciphertext modulus q = 2^{32}. Then, we do all of the math in `pir.h` and `pir.c` using 32-bit integers (i.e., `uint32_t`).

**Comment by matsutakk** [comment]
なるほど、そうなんですね。

おかげさまで、overflowによるmodulusの実装について、新しい発見がありました。(https://users.cs.utah.edu/~regehr/papers/overflow12.pdf)

ありがとうございます。

**Comment by matsutakk** [comment]
I see.

I learned new thing implementing the modulus by overflow behavior.
(https://users.cs.utah.edu/~regehr/papers/overflow12.pdf)

Thank you.
